[package]
name = "tsync"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
argh = "0.1.13"
byteorder = "1.5.0"
postcard = { version = "1.1.1", features = ["alloc"] }
serde = { version = "1.0.219", features = ["derive"] }
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
